title: ARK Portal Data Model Dictionary
description: A public resource detailing the attributes and values for the ARK Portal data model
theme: just-the-docs
logo: "images/ark_portal_logo.svg"
color_scheme: ark
favicon_ico: "images/favicon.svg"

# silence sass deprecation warning about darken() function
sass:
  quiet_deps: true

# set callout formatting
callouts:
  highlight:
    title: Attention
    color: yellow
  warning:
    title: WARNING
    color: red
  note: 
    title: Note
    color: purple

aux_links:
  "Visit the ARK Portal": 
  - "https://arkportal.synapse.org/"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# External navigation links
nav_external_links:
  - title: ARK Portal
    url: "https://arkportal.synapse.org/"
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true
  - title: ARK Portal Data Model
    url: "https://github.com/ARK-Portal/data_model/tree/main"
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true

### SEARCH BAR ### 
# Enable or disable the site search
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  search.heading_level: 2
  # search result preview config
  # Maximum amount of previews per search result
  search.previews: 6
  # Maximum amount of words to display before a matched word in the preview
  search.preview_words_before: 6
  # Maximum amount of words to display after a matched word in the preview
  search.preview_words_after: 6




