synapse:
  master_fileview: 'syn23643253'
  manifest_folder: 'manifests'
  manifest_filename: 'synapse_storage_manifest.csv'
  token_creds: 'syn23643259'
  service_acct_creds: 'syn25171627'

asset_store:
  synapse:
    config: ".synapseConfig"
    manifest_basename: 'synapse_storage_manifest'
    master_fileview_id:  'syn64411960'

google_sheets:
  service_acct_creds: "schematic_service_account_creds.json"
  strict_validation: true

style:
  google_manifest:
    req_bg_color:
      red: 0.9215
      green: 0.9725
      blue: 0.9803
    opt_bg_color:
      red: 1.0
      green: 1.0
      blue: 0.9019
    master_template_id: '1LYS5qE4nV9jzcYw5sXwCza25slDfRA1CIg3cs-hCdpU'
    strict_validation: true
