# This config has the same default values as schematic itself has
asset_store:
  synapse:
    config: ".synapseConfig"
    manifest_basename: 'synapse_storage_manifest'
    master_fileview_id:  'syn64411960'

google_sheets:
  service_acct_creds: "schematic_service_account_creds.json"
  strict_validation: true
