# This config has the same default values as schematic itself has
manifest:
  manifest_folder:  'manifests'
  title: 'example'

model:
  location: 'ark.model.jsonld'

google_sheets:
  service_acct_creds: "schematic_service_account_creds.json"
  strict_validation: true
