# This config has the same default values as schematic itself has
asset_store:
  synapse:
    config: "/Users/jvera/.synapseConfig"
    manifest_basename: 'synapse_storage_manifest'
    master_fileview_id:  'syn64411960'

manifest:
  manifest_folder:  'manifests'
  title: 'example'

model:
  location: 'ark.model.jsonld'

google_sheets:
  service_acct_creds: "schematic_service_account_creds.json"
  strict_validation: true
