# This workflow is used to update gh-pages content by running an R workflow when 
# changes occur to ark.model.csv in the main branch

name: ci gh-pages content update

on:
  push:
    branches: ["main", "gh-pages"]
    paths: 
      - 'ark.model.csv'
      - '.github/workflows/ci-gh-pages.yml'
      - '_utils/**'
      - 'tempaltes/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    name: Update site content
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup R env
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rmarkdown
            any::dplyr
            any::stringr
            any::glue
            any::purrr
            any::snakecase
            any::readr
            any::sys
            any::lubridate

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Update site content
        run: | 
          Rscript _utils/update_site_content.R
      
      - name: Commit files if there are changes
        run: |
          if [[ $(git diff --exit-code) ]]; then 
            echo "Changes in site content detected and will be committed."
            git config --local user.name "$GITHUB_ACTOR"
            git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git add .
            git commit -m "GitHub Action: update data dictionary site content"
          else 
            echo "Trigger even changes did not affect site content, nothing to commit"
          fi
    
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: gh-pages
         force: true
# END