# This workflow is used to update gh-pages content by running an R workflow when 
# changes occur to ark.model.csv in the main branch

name: ci-schema-convert

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Set up supported python.
      - name: Setup R env
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rmarkdown
            
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          path: gh-pages
        
      - name: Hello world test
        run: Rscript _utils/hello_world.R
