# This workflow is used to update gh-pages content by running an R workflow when
# changes occur directly to files the produce site content in the gh-pages branch

name: ci gh-pages content update

on:
  push:
    branches: ["gh-pages", "main"]
    paths:
      - '.github/workflows/ci-gh-pages.yml'
      - '_utils/update_site_content.R'
      - 'ark.model.csv'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    name: Update site content
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ARK_CICD_SERVICE_ACCOUNT }}

    steps:
      - name: Setup R env
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: '4.3.3'

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::stringr
            any::glue
            any::purrr
            any::snakecase
            any::rlang
            any::remotes
            any::lubridate

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.ARK_CICD_SERVICE_ACCOUNT }}

      - name: Update site content
        run: |
          Rscript _utils/update_site_content.R https://raw.githubusercontent.com/ARK-Portal/data_model/refs/heads/main/ark.model.csv

      - name: Commit files if there are changes
        run: |
          if [[ $(git diff --exit-code) ]]; then
            echo "Changes in site content detected and will be committed."
            git config --local user.name "ark-cicd-service-account"
            git config --local user.email "ark-cicd-service-account@users.noreply.github.com"
            git add .
            git commit -m "GitHub Action: update data dictionary site content"
          else
            echo "Push to branch did not change site content, nothing to commit"
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ARK_CICD_SERVICE_ACCOUNT }}
          branch: gh-pages
          force: true
