name: ci-schema-convert

on:
  push:
    branches: [mk_templates]
    paths: 

env:
  SCHEMATIC_VERSION: 24.12.1

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SCHEMATIC_SERVICE_ACCOUNT_CREDS: ${{ secrets.TEST_JSON }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      # Set up supported python.
      - name: test json write
        run: |
          bash utils/test_json.sh
      - name: reveal fake json
        run: |
          cat schematic_service_account_creds.json
